name: CI

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ["4.0.5", stable, nightly]
        target: [html5, hl, neko, flash]
        exclude:
        - {haxe-version: "3.4.7", target: hl}
        - {haxe-version: nightly, target: html5}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: lix-pm/setup-lix@master
    - uses: actions/checkout@v2
    - run: haxelib dev flixel-tools .
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: ${{matrix.haxe-version}}
        flixel-versions: dev
        target: ${{matrix.target}}
    - run: |
        cd ${{env.HAXELIB_REPO}}/flixel-tools/git
        npm install
        cd ..
        haxelib run flixel-tools tpl -n "default"
        cd default
        haxelib run lime build ${{matrix.target}}
